# Generated by Django 5.2.3 on 2025-06-15 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='student full name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='student email')),
                ('semester', models.CharField(blank=True, choices=[('SEM_ONE', 'Semester one'), ('SEM_TWO', 'Semester two'), ('SEM_THREE', 'Semester three'), ('SEM_FOUR', 'Semester four'), ('SEM_FIVE', 'Semester five'), ('SEM_SIX', 'Semester six'), ('SEM_SEVEN', 'Semester seven'), ('SEM_EIGHT', 'Semester eight')], default='N/A', max_length=10, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='teacher full name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Teacher email')),
                ('department', models.CharField(blank=True, choices=[('BCA', 'Bachelor in computer application'), ('BCT', 'Bachelor in electronics and information'), ('BCE', 'Bachelor in civil Engineering')], default='N/A', max_length=5, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
