# Generated by Django 5.2.3 on 2025-06-17 07:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='student full name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='student email')),
                ('semester', models.CharField(blank=True, choices=[('SEM_ONE', 'Semester one'), ('SEM_TWO', 'Semester two'), ('SEM_THREE', 'Semester three'), ('SEM_FOUR', 'Semester four'), ('SEM_FIVE', 'Semester five'), ('SEM_SIX', 'Semester six'), ('SEM_SEVEN', 'Semester seven'), ('SEM_EIGHT', 'Semester eight')], default='N/A', max_length=10, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='teacher full name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Teacher email')),
                ('department', models.CharField(blank=True, choices=[('BCA', 'Bachelor in computer application'), ('BCT', 'Bachelor in electronics and information'), ('BCE', 'Bachelor in civil Engineering')], default='N/A', max_length=5, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='material')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('description', models.CharField(max_length=200, verbose_name='Material description')),
                ('subject', models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis'), ('BCT003', 'Operating Systems'), ('BCT004', 'Instrumentation')], default='N/A', max_length=20, verbose_name='subject')),
                ('files', models.FileField(upload_to='material/', verbose_name='Select file')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2025, 6, 17, 13, 35, 9, 92057), verbose_name='upload Date')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Material ',
                'verbose_name_plural': 'MAterials',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignmenyt Title')),
                ('start_date', models.DateField(default='Start date', verbose_name='start date')),
                ('end_date', models.DateField(default='End Date', verbose_name='End Date')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='assignments/questions/', verbose_name='Assignment question files')),
                ('question', models.TextField(blank=True, null=True, verbose_name='assignment questions')),
                ('remark', models.CharField(max_length=100, verbose_name='assignment Details')),
                ('full_mark', models.FloatField()),
                ('subject', models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis'), ('BCT003', 'Operating Systems'), ('BCT004', 'Instrumentation')], default='N/A', max_length=20, verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'Assignment ',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-title'],
            },
        ),
    ]
