# Generated by Django 5.2.3 on 2025-06-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_material_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title'], 'verbose_name': 'Material ', 'verbose_name_plural': 'MAterials'},
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 14, 38, 19, 144289), verbose_name='upload Date'),
        ),
    ]
