# Generated by Django 5.2.3 on 2025-06-19 07:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_material_options_alter_material_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-title'], 'verbose_name': 'assignment', 'verbose_name_plural': 'assignments'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title'], 'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='files',
            new_name='material_file',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_subject',
            field=models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating System'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Assignment Subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_subject',
            field=models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating System'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Material Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Assignment Question'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/questions/', verbose_name='Select Assignment File'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='remark',
            field=models.CharField(max_length=100, verbose_name='Assignment Details'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Assignment Title'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('TEXT_BOOK', 'A text book'), ('REFERENCE_BOOK', 'A reference book'), ('OLD_QUESTION', 'Previous board exam question'), ('AUDIO_BOOK', 'An audio book')], max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Material Title'),
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Student Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Student Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Teacher Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Teacher Full Name'),
        ),
    ]
